Algoritmo "AlgoritmoDecisão"
// Disciplina   : [Linguagem e Lógica de Programação com VisualG]
// Professor   : Jainson Costa Dos Santos
// Descrição   : Demonstrar estrutura de decisão.
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   numero1:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(numero1)
   se numero1<10 entao
      escreval("O número digitado é menor que 10")
   fimse

Fimalgoritmo