Algoritmo "retangulo"
// Disciplina   :[Lógica de Programação com VisualG]
// Professor   : Jainson Costa Dos Santos
// Descrição   : Solicita dois números inteiros para o
// usuário, multiplica a base e altura de um retângulo e exibe o
// resultado da àrea
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 26/03/2026
Var
   // Seção de Declarações das variáveis
   altura, area, base: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor da base: ")
   leia(base)
   escreva("Digite o valor da altura: ")
   leia(altura)
   area <-altura*base
   escreva("A area de um retângulo é: ",area)

Fimalgoritmo