Algoritmo "paralelograma"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jainson Costa Dos Santos
// Descrição   : Solicita a base e a altura,
// multiplicando os dois e exibindo a área
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   base: real
   altura: real
   area: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite a base do paralelograma: ")
   leia(base)
   escreval("")
   escreva("Digite a altura do paralelograma: ")
   leia(altura)
   area <- base*altura
   escreval("")
   escreva("A área de um Paralelograma é: ", area)
   escreval("")

Fimalgoritmo