Algoritmo "Divisão"
// Disciplina   : [Lógica de Programação]
// Professor   : Jainson Costa Dos Santos
// Descrição   : Solicita dois números reais para o usuário,
// divide e exibe o resultado
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
     numero1: real
     numero2: real
     resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Digite um número: ")
     leia(numero1)
     escreva("Digite um outro número: ")
     leia(numero2)
     resultado<-numero1/numero2
     escreva("A divisão dos dois números é: ", resultado)
     leia(resultado)

Fimalgoritmo