Algoritmo "RaioCirculo"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jainson Costa Dos Santos
// Descrição   : Solicita o raio do círculo e exibe o
// perímetro da circuferência
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
     raio: real
     resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Digite o raio do círculo: ")
     leia(raio)
     escreval("")
     resultado <-2 * 3.14 * raio
     escreva("O valor do perímetro da circuferência é: ", resultado)

Fimalgoritmo