Algoritmo "Soma"
// Disciplina   :[Lógica de Programação com VisualG]
// Professor   : Jainson Costa dos Santos
// Descrição   : Solicita dois números para o
// usuário, soma e exibe o resultado
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
         numero1:inteiro
         numero2:inteiro
         resultado:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Digite um número inteiro: ")
     leia(numero1)
     escreva("Digite um outro número inteiro: ")
     leia(numero2)
     resultado<-numero1+numero2
     escreva("A soma dos números digitados é: " ,resultado)
     leia(resultado)

Fimalgoritmo