Algoritmo "SOMAINTEIRO"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Faça um contador repetir o número até 100 e ver a soma total
// Autor(a)    : Henry Cardoso
// Data atual  : 06/04/2026
Var
   // Seção de Declarações das variáveis
   contadora, somadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora <- 1

   enquanto contadora < 101 faca
      somadora <- somadora + contadora
      contadora <- contadora + 1
   fimenquanto

   escreva("Resultado da soma até 100 é: ", somadora)
Fimalgoritmo
