Algoritmo "Subtração"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jainson Costa Dos Santos
// Descrição   : Solicita dois números inteiros para o
// usuário, subtrai e exibe o resultado
// Autor(a)    : Henry Cardoso Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
     numero1: inteiro
     numero2: inteiro
     resultado: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Digite um número: ")
     leia(numero1)
     escreva("Digite outro número: ")
     leia(numero2)
     resultado<-numero1-numero2
     escreva("A subtração dos dois números é: ",resultado)
     leia(resultado)
Fimalgoritmo