Algoritmo "Tabuada"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Digite um número inteiro e veja a multiplação do 1 ao 10.
// Autor(a)    : Henry Cardoso
// Data atual  : 06/04/2026
Var
   // Seção de Declarações das variáveis
   contadora, numero, resultado: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("Digite o valor")
   leia (numero)
   Para contadora de 1 ate 10 faça
      resultado <- numero * contadora
      Escreval(numero, " x", contadora, " =", resultado)
   fimpara

Fimalgoritmo